version: '3'
services:
  telldus_mqtt:
    build:
      context: .
      dockerfile: /.docker/telldus/Dockerfile
    ports:
      - "9005:9005"
      - "16926:16926"
    volumes:
      - /src/config:/var/www/html/config/
    environment:
      - CRON_USER=root
      - CRON_SCHEDULE=* * * * *
      - CRON_COMMAND=/usr/local/bin/php -f /var/www/html/mqtt_push.php
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    network_mode: host