FROM php:7.2-apache

#RUN apt-get update && apt-get install -y libmemcached-dev zlib1g-dev \
#	&& pecl install Mosquitto-alpha

COPY src/ /var/www/html/

RUN chmod 777 /var/www/html/config/


# Install cron
RUN apt-get update && apt-get install -y cron

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Add crontab file in the cron directory
ADD /.docker/telldus/crontab /etc/cron.d/hello-cron

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/hello-cron

RUN /usr/bin/crontab /etc/cron.d/hello-cron

# Setup cron job
#RUN (crontab -l ; echo “* * * * * echo “Hello world” >> /var/log/cron.log”) | crontab

# Run the command on container startup
#CMD [“cron”, “-f”]
#CMD cron && tail -f /var/log/cron.log

#CMD ["cron", "-f"]
#CMD [ "sh", "-c", "apache2 && cron -f" ]
CMD ["/bin/bash", "/var/www/html/startup.sh"]



COPY /.docker/telldus/ports.conf /etc/apache2/ports.conf
COPY /.docker/telldus/vhost.conf /etc/apache2/sites-available/000-default.conf